https://code.visualstudio.com/api/working-with-extensions/continuous-integration#azure-pipelines
https://stackoverflow.com/questions/58192624/publishing-vs-code-extension-via-azure-devops
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?tabs=classic%2Cbatch&view=azure-devops#secret-variables


trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'install node'

- bash: |
    npm install vsce --save-dev
  displayName: 'install vsce'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1
  displayName: start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    yarn && yarn compile
    cd sample
    yarn && yarn compile && yarn test
  displayName: test
  env:
    DISPLAY: ':99.0'

- bash: |
    yarn deploy
  displayName: publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['Agent.OS'], 'Linux'))
  env:
    VSCE_PAT: $(VSCE_PAT)